AWSTemplateFormatVersion: "2010-09-09"
Description: Create parameter for System Prefix

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  SystemPrefix:
    Type: String
    Default: kadai1

# ------------------------------------------------------------#
#  Resources Parameters
# ------------------------------------------------------------#
Resources:
  SystemPrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SystemPrefixParameter
      Description: System Prefix
      Type: String
      Value: !Ref SystemPrefix

# ------------------------------------------------------------#
# Outputs
# ------------------------------------------------------------#
Outputs:
  SystemPrefixParameter:
    Description: System Prefix
    Value: !Ref SystemPrefixParameter
    Export:
      Name: SystemPrefixParameter