AWSTemplateFormatVersion: '2010-09-09'
Description: "Create for Aurora Cluster"

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "DB Configuration"
        Parameters:
          - SystemPrefix
          - EnvPrefix

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  SystemPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: SystemPrefix

  EnvPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: EnvPrefix

# ------------------------------------------------------------#
#  Resources Parameters
# ------------------------------------------------------------#
Resources:
  AuroraDBCluster:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      MasterUsername: !Sub '{{resolve:secretsmanager:${AuroraDBClusterAdminAccount}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${AuroraDBClusterAdminAccount}:SecretString:password}}'
      #DatabaseName: !Sub ${SystemPrefix}-${EnvPrefix}-DB
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '02:00-03:00'
      #EngineMode: provisioned
      EngineVersion: 8.0.mysql_aurora.3.05.0
      StorageEncrypted: true
      #AvailabilityZones:
      #  - ap-northeast-1a
      #  - ap-northeast-1c
      DBClusterIdentifier: !Sub ${SystemPrefix}-${EnvPrefix}-DB
      DBSubnetGroupName: !Ref AuroraDBClusterSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue DBSG
      Tags:
        - Key: Name
          Value: !Sub ${SystemPrefix}-${EnvPrefix}-DB
        - Key: System
          Value: !Sub ${SystemPrefix}
        - Key: Environment
          Value: !Sub ${EnvPrefix}

  AuroraDBClusterSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora
      SubnetIds:
        - !ImportValue PrivateSubnetA
        - !ImportValue PrivateSubnetC

#  AuroraDBParameterGroup:
#    Type: AWS::RDS::DBParameterGroup
#    Properties:
#      Family: aurora-mysql5.7
#      Description: Aurora DB Parameter Group
#      Parameters:
#        key: value

  AuroraDBClusterAdminAccount:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${SystemPrefix}-${EnvPrefix}-DB-AdminAccount
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: !Join [ '', [ ' ', '"', '#', '$', "'", '/', '@', '=', '\\', '`' ] ]

  AuroraDBClusterAdminAccountAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      TargetType: AWS::RDS::DBInstance
      TargetId: !Ref AuroraDBCluster
      SecretId: !Ref AuroraDBClusterAdminAccount
